# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serkit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie 
from PyQt5.QtCore import QPropertyAnimation, pyqtProperty,QTimer
from PyQt5.QtWidgets import QFileDialog
import allModules
import pygame



pygame.mixer.pre_init(4000, 16, 1, 4096)
# pygame.mixer.pre_init(1000, 16, 1, 512)
pygame.init()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1238, 775)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(85, 239, 196, 255));\n"
"")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(760, 30, 111, 41))
        self.pushButton.setStyleSheet("QPushButton#pushButton\n"
                                      "{\n"
                                      "background-color:rgba(0,0,0,0);\n"
                                      "border:none;\n"
                                      "border-bottom:2px solid rgba(255,255,255,255);\n"
                                      "color: rgb(85, 239, 196);\n"
                                      "padding:7px;\n"
                                      "font: 75 11pt \"Arial\";\n"
                                      "}\n"
                                      "QPushButton#pushButton:hover\n"
                                      "{\n"
                                      "background-color: rgb(39, 165, 129);\n"
                                      "color:rgb(255,255,255);\n"
                                      "padding:7px;\n"
                                      "border-radius: 20%;\n"
                                      "border:none;\n"
                                      "border-bottom:2px solid rgba(255,255,255,0);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page))
        
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 30, 111, 41))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2\n"
                                        "{\n"
                                        "background-color:rgba(0,0,0,0);\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,255);\n"
                                        "color: rgb(85, 239, 196);\n"
                                        "padding:7px;\n"
                                        "font: 75 11pt \"Arial\";\n"
                                        "}\n"
                                        "QPushButton#pushButton_2:hover\n"
                                        "{\n"
                                        "background-color: rgb(39, 165, 129);\n"
                                        "color:rgb(255,255,255);\n"
                                        "padding:7px;\n"
                                        "border-radius: 20%;\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,0);\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_2))
        
        
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1000, 30, 111, 41))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3\n"
                                        "{\n"
                                        "background-color:rgba(0,0,0,0);\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,255);\n"
                                        "color: rgb(85, 239, 196);\n"
                                        "padding:7px;\n"
                                        "font: 75 11pt \"Arial\";\n"
                                        "}\n"
                                        "QPushButton#pushButton_3:hover\n"
                                        "{\n"
                                        "background-color: rgb(39, 165, 129);\n"
                                        "color:rgb(255,255,255);\n"
                                        "padding:7px;\n"
                                        "border-radius: 20%;\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,0);\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.tryit)
        
        
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(1120, 30, 111, 41))
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4\n"
                                        "{\n"
                                        "background-color:rgba(0,0,0,0);\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,255);\n"
                                        "color: rgb(85, 239, 196);\n"
                                        "padding:7px;\n"
                                        "font: 75 11pt \"Arial\";\n"
                                        "}\n"
                                        "QPushButton#pushButton_4:hover\n"
                                        "{\n"
                                        "background-color: rgb(39, 165, 129);\n"
                                        "color:rgb(255,255,255);\n"
                                        "padding:7px;\n"
                                        "border-radius: 20%;\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,0);\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.share)
        
        
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 341, 91))
        self.label.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                 "color: rgb(85, 239, 196);\n"
                                 "\n"
                                 "")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1241, 861))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("scifi-hud-4k-c1.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 130, 1191, 631))
        self.stackedWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(80, 90, 651, 481))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(71, 197, 163);")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(40, 50, 1081, 541))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 120);\n"
                                 "border-radius:50%;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.label_3.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 1141, 441))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                   "color: rgb(71, 197, 163);")
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 510, 181, 41))
        self.pushButton_5.setStyleSheet("\n"
                                        "background-color: rgb(39, 165, 129);\n"
                                        "color:rgb(255,255,255);\n"
                                        "padding:7px;\n"
                                        "border-radius: 20%;\n"
                                        "font: 75 14pt \"Arial\";\n"
                                        "")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.tryit)
        
        
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 1151, 581))
        self.frame_2.setStyleSheet("background-color: rgba(0, 0, 0, 120);\n"
                                   "border-radius:50%;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.label_4.raise_()
        self.pushButton_5.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_5 = QtWidgets.QFrame(self.page_3)
        self.frame_5.setGeometry(QtCore.QRect(320, 110, 601, 401))
        self.frame_5.setStyleSheet("border:none;\n"
                                   "border:2px solid rgb(255,255,255);\n"
                                   "background-color:rgba(0,0,0,200);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(70, 50, 461, 301))
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        
        self.movie = QMovie("sneutral.gif") 
        self.label_5.setMovie(self.movie) 
        self.movie.start() 
        
        self.pushButton_8 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_8.setGeometry(QtCore.QRect(470, 30, 281, 41))
        self.pushButton_8.setStyleSheet("QPushButton#pushButton_8\n"
                                        "{\n"
                                        "background-color:rgba(0,0,0,180);\n"
                                        "border:none;\n"
                                        "border-radius:20%;\n"
                                        "border:2px solid rgba(255,255,255,255);\n"
                                        "color: rgb(85, 239, 196);\n"
                                        "padding:7px;\n"
                                        "font: 75 11pt \"Arial\";\n"
                                        "}\n"
                                        "QPushButton#pushButton_8:hover\n"
                                        "{\n"
                                        "background-color: rgb(39, 165, 129);\n"
                                        "color:rgb(255,255,255);\n"
                                        "padding:7px;\n"
                                        "border-radius: 20%;\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,0);\n"
                                        "}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.chfile)
        
        
        self.pushButton_15 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_15.setGeometry(QtCore.QRect(1140, 580, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(26)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton#pushButton_15\n"
                                         "{\n"
                                         "background-color:rgba(0,0,0,0);\n"
                                         "color: rgb(85, 239, 196);\n"
                                         "border-radius:20%;\n"
                                         "}\n"
                                         "QPushButton#pushButton_15:hover\n"
                                         "{\n"
                                         "background-color: rgb(85, 239, 196);\n"
                                         "color:rgb(255,255,255);\n"
                                         "border-radius: 20%;\n"
                                         "}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.msg2)
        
        
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_13.setGeometry(QtCore.QRect(470, 30, 281, 41))
        self.pushButton_13.setStyleSheet("QPushButton#pushButton_13\n"
                                         "{\n"
                                         "background-color:rgba(0,0,0,180);\n"
                                         "border:none;\n"
                                         "border-radius:20%;\n"
                                         "border:2px solid rgba(255,255,255,255);\n"
                                         "color: rgb(85, 239, 196);\n"
                                         "padding:7px;\n"
                                         "font: 75 11pt \"Arial\";\n"
                                         "}\n"
                                         "QPushButton#pushButton_13:hover\n"
                                         "{\n"
                                         "background-color: rgb(39, 165, 129);\n"
                                         "color:rgb(255,255,255);\n"
                                         "padding:7px;\n"
                                         "border-radius: 20%;\n"
                                         "border:none;\n"
                                         "border-bottom:2px solid rgba(255,255,255,0);\n"
                                         "}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.record)
        
        self.frame_6 = QtWidgets.QFrame(self.page_4)
        self.frame_6.setGeometry(QtCore.QRect(320, 110, 601, 401))
        self.frame_6.setStyleSheet("border:none;\n"
                                   "border:2px solid rgb(255,255,255);\n"
                                   "background-color:rgba(0,0,0,200);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(70, 50, 461, 301))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        
        self.movie = QMovie("sneutral.gif") 
        self.label_6.setMovie(self.movie) 
        self.movie.start() 
        
        self.pushButton_14 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_14.setGeometry(QtCore.QRect(1140, 580, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(26)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton#pushButton_14\n"
                                         "{\n"
                                         "background-color:rgba(0,0,0,0);\n"
                                         "color: rgb(85, 239, 196);\n"
                                         "border-radius:20%;\n"
                                         "}\n"
                                         "QPushButton#pushButton_14:hover\n"
                                         "{\n"
                                         "background-color: rgb(85, 239, 196);\n"
                                         "color:rgb(255,255,255);\n"
                                         "border-radius: 20%;\n"
                                         "}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.msg1)
        
        
        self.stackedWidget.addWidget(self.page_4)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(1240, 70, 201, 211))
        self.frame_3.setStyleSheet("background-color: rgba(0, 0, 0, 200);\n"
                                   "border-radius:50%;\n"
                                   "border:none;\n"
                                   "border: 2px solid rgb(255,255,255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 40, 141, 41))
        self.pushButton_6.setStyleSheet("QPushButton#pushButton_6\n"
                                        "{\n"
                                        "background-color:rgba(0,0,0,0);\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,255);\n"
                                        "color: rgb(85, 239, 196);\n"
                                        "padding:7px;\n"
                                        "font: 75 11pt \"Arial\";\n"
                                        "}\n"
                                        "QPushButton#pushButton_6:hover\n"
                                        "{\n"
                                        "background-color: rgb(39, 165, 129);\n"
                                        "color:rgb(255,255,255);\n"
                                        "padding:7px;\n"
                                        "border-radius: 20%;\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,0);\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(lambda: self.refresh(self.page_3))
        
        
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 110, 141, 41))
        self.pushButton_7.setStyleSheet("QPushButton#pushButton_7\n"
                                        "{\n"
                                        "background-color:rgba(0,0,0,0);\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,255);\n"
                                        "color: rgb(85, 239, 196);\n"
                                        "padding:7px;\n"
                                        "font: 75 11pt \"Arial\";\n"
                                        "}\n"
                                        "QPushButton#pushButton_7:hover\n"
                                        "{\n"
                                        "background-color: rgb(39, 165, 129);\n"
                                        "color:rgb(255,255,255);\n"
                                        "padding:7px;\n"
                                        "border-radius: 20%;\n"
                                        "border:none;\n"
                                        "border-bottom:2px solid rgba(255,255,255,0);\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(lambda: self.refresh(self.page_4))
        
        
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(1440, 70, 161, 201))
        self.frame_4.setStyleSheet("background-color: rgba(0, 0, 0, 200);\n"
                                   "border-radius:50%;\n"
                                   "border:none;\n"
                                   "border: 2px solid rgb(255,255,255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(26)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton#pushButton_9\n"
                                        "{\n"
                                        "background-color:rgba(0,0,0,0);\n"
                                        "color: rgb(85, 239, 196);\n"
                                        "border-radius:20%;\n"
                                        "border:none;\n"
                                        "border: 2px solid rgba(255,255,255,0);\n"
                                        "}\n"
                                        "QPushButton#pushButton_9:hover\n"
                                        "{\n"
                                        "background-color: rgb(85, 239, 196);\n"
                                        "color:rgb(255,255,255);\n"
                                        "border-radius: 20%;\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(26)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton#pushButton_10\n"
                                         "{\n"
                                         "background-color:rgba(0,0,0,0);\n"
                                         "color: rgb(85, 239, 196);\n"
                                         "border:none;\n"
                                         "border: 2px solid rgba(255,255,255,0);\n"
                                         "border-radius:20%;\n"
                                         "}\n"
                                         "QPushButton#pushButton_10:hover\n"
                                         "{\n"
                                         "background-color: rgb(85, 239, 196);\n"
                                         "color:rgb(255,255,255);\n"
                                         "border-radius: 20%;\n"
                                         "}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setGeometry(QtCore.QRect(90, 110, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(26)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton#pushButton_11\n"
                                         "{\n"
                                         "background-color:rgba(0,0,0,0);\n"
                                         "color: rgb(85, 239, 196);\n"
                                         "border-radius:20%;\n"
                                         "border:none;\n"
                                         "border: 2px solid rgba(255,255,255,0);\n"
                                         "}\n"
                                         "QPushButton#pushButton_11:hover\n"
                                         "{\n"
                                         "background-color: rgb(85, 239, 196);\n"
                                         "color:rgb(255,255,255);\n"
                                         "border-radius: 20%;\n"
                                         "}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 110, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(26)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton#pushButton_12\n"
                                         "{\n"
                                         "background-color:rgba(0,0,0,0);\n"
                                         "color: rgb(85, 239, 196);\n"
                                         "border-radius:20%;\n"
                                         "border:none;\n"
                                         "border: 2px solid rgba(255,255,255,0);\n"
                                         "}\n"
                                         "QPushButton#pushButton_12:hover\n"
                                         "{\n"
                                         "background-color: rgb(85, 239, 196);\n"
                                         "color:rgb(255,255,255);\n"
                                         "border-radius: 20%;\n"
                                         "}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(1240, 510, 181, 211))
        self.frame_7.setStyleSheet("background-color: rgba(0, 0, 0, 200);\n"
                                   "border-radius:50%;\n"
                                   "border:none;\n"
                                   "border: 2px solid rgb(255,255,255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 151, 171))
        self.label_7.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                   "color: rgb(85, 239, 196);\n"
                                   "font: 10pt \"MS Shell Dlg 2\";\n"
                                   "border:20%")
        self.label_7.setObjectName("label_7")
        self.frame_8 = QtWidgets.QFrame(Form)
        self.frame_8.setGeometry(QtCore.QRect(1420, 510, 171, 211))
        self.frame_8.setStyleSheet("background-color: rgba(0, 0, 0, 200);\n"
                                   "border-radius:50%;\n"
                                   "border:none;\n"
                                   "border: 2px solid rgb(255,255,255);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 151, 171))
        self.label_8.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                   "color: rgb(85, 239, 196);\n"
                                   "font: 10pt \"MS Shell Dlg 2\";\n"
                                   "border:20%")
        self.label_8.setObjectName("label_8")
        
        self.label_9 = QtWidgets.QLabel(self.page_4)
        self.label_9.setGeometry(QtCore.QRect(470,550,281,41))
        self.label_9.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                   "border:none;\n"
                                   "border-radius:20%;\n"
                                   "border:2px solid rgba(255,255,255,255);\n"
                                   "color: rgb(85, 239, 196);\n"
                                   "padding-left:100px;\n"
                                   "font: 75 12pt \"Arial\";\n")
        self.label_9.setObjectName("label_9")
        
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(470,550,281,41))
        self.label_10.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                    "border:none;\n"
                                    "border-radius:20%;\n"
                                    "border:2px solid rgba(255,255,255,255);\n"
                                    "color: rgb(85, 239, 196);\n"
                                    "padding-left:100px;\n"
                                    "font: 75 12pt \"Arial\";\n")
        self.label_10.setObjectName("label_10")
        
        self.pushButton_16 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_16.setGeometry(QtCore.QRect(770,20,51,51))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(26)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton#pushButton_16\n"
                                         "{\n"
                                         "background-color:rgba(0,0,0,0);\n"
                                         "color: rgb(85, 239, 196);\n"
                                         "border-radius:20%;\n"
                                         "}\n"
                                         "QPushButton#pushButton_16:hover\n"
                                         "{\n"
                                         "background-color: rgb(85, 239, 196);\n"
                                         "color:rgb(255,255,255);\n"
                                         "border-radius: 20%;\n"
                                         "}")
        self.pushButton_16.setObjectName("pushButton_16")
        
        
             
        
        
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_16.raise_()
        self.label.raise_()
        self.stackedWidget.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_7.raise_()
        self.frame_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
       

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "ABOUT US"))
        self.pushButton_2.setText(_translate("Form", "HOME"))
        self.pushButton_3.setText(_translate("Form", "TRY IT"))
        self.pushButton_4.setText(_translate("Form", "SHARE"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:600;\">    SER</span><span style=\" font-size:48pt; font-weight:600; color:#ffffff;\">kit</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">ABOUT US</span></p><p><br/></p><p><span style=\" font-size:24pt;\">FRONTEND DEVELOPERS:</span></p><p><span style=\" font-size:16pt; color:#ffffff;\">KRATIKA </span></p><p><span style=\" font-size:16pt; color:#ffffff;\">GARIMA AGARWAL</span></p><p><br/></p><p><span style=\" font-size:24pt;\">BACKEND DEVELOPERS:</span></p><p><span style=\" font-size:16pt; color:#ffffff;\">DHAIRYA HANS</span></p><p><span style=\" font-size:16pt; color:#ffffff;\">DEVANSH BHATNAGAR</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">SERkit is an abbreviation of Speech Emotion</span></p><p><span style=\" font-size:26pt; font-weight:600;\">Recognition kit. </span></p><p><br/></p><p><span style=\" font-size:18pt; color:#ffffff;\">This tool helps in recognizing the emotions from audio inputs.</span></p><p><span style=\" font-size:18pt; color:#ffffff;\">It is a project that helps in practical implementation of </span></p><p><span style=\" font-size:18pt; color:#ffffff;\">Data Science and Machine Learning.</span></p><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Check out this amazing tool that brings technology and </span></p><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">emotions together!! </span></p></body></html>"))
        self.pushButton_5.setText(_translate("Form", "TRY IT!!"))
        self.pushButton_8.setText(_translate("Form", "CHOOSE FILE"))
        self.pushButton_15.setText(_translate("Form", "k"))
        self.pushButton_16.setText(_translate("Form", "M"))
        self.pushButton_13.setText(_translate("Form", "START RECORDING"))
        self.pushButton_14.setText(_translate("Form", "k"))
        self.pushButton_6.setText(_translate("Form", "UPLOAD"))
        self.pushButton_7.setText(_translate("Form", "RECORD"))
        self.pushButton_9.setText(_translate("Form", "E"))
        self.pushButton_10.setText(_translate("Form", "Q"))
        self.pushButton_11.setText(_translate("Form", "D"))
        self.pushButton_12.setText(_translate("Form", "C"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p>Press the start</p><p>recording button </p><p>and say something.</p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p>Choose an audio file</p><p> and see the results!</p></body></html>"))
       
        
       
    def refresh(self, p):
    
        self.stackedWidget.setCurrentWidget(p) 
        self.movie = QMovie("sneutral.gif") 
        self.label_5.setMovie(self.movie) 
        self.movie.start()
        self.label_10.setText("")
        self.label_6.setMovie(self.movie) 
        self.movie.start()
        self.label_9.setText("")
        pos1=self.frame_3.pos()
        if pos1.x()==1000:
            self.animation1=QPropertyAnimation(self.frame_3, b"pos")
            self.animation1.setDuration(250)
            self.animation1.setStartValue(QtCore.QPoint(1000,80))
            self.animation1.setEndValue(QtCore.QPoint(1240,80))
            self.animation1.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation1.start()
            
        pos2=self.frame_4.pos()
        if pos2.x()==1050:
            self.animation2=QPropertyAnimation(self.frame_4, b"pos")
            self.animation2.setDuration(250)
            self.animation2.setStartValue(QtCore.QPoint(1050,80))
            self.animation2.setEndValue(QtCore.QPoint(1440,80))
            self.animation2.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation2.start()
            
    def chfile(self):
        # open and choose a file from OPEN dialog box
        path = QFileDialog.getOpenFileName() 
        print(path[0])
        p = path[0].split('/')
        f = '\\'.join(p)
        pygame.mixer.music.load(f)
        self.pushButton_16.clicked.connect(lambda :  pygame.mixer.music.play())
        result=allModules.predictions(f)
        emotion=result[0]
        self.label_10.setText(emotion)
        emotions="s"+emotion+".gif"
        self.movie = QMovie(emotions) 
        self.label_5.setMovie(self.movie) 
        self.movie.start()
       
        
    def record(self):
        # record live
        # need to provide the path of recorded file. here f is the apth of the recorded file
        f = allModules.record()
        result=allModules.predictions(f)
        emotion=result[0]
        emotions="s"+emotion+".gif"
        self.movie = QMovie(emotions) 
        self.label_6.setMovie(self.movie) 
        self.movie.start()
        self.label_9.setText(emotion)
        
        
        
        
    def tryit(self):
        # opening the slide menu
        pos2=self.frame_4.pos()
        if pos2.x()==1050:
            self.animation2=QPropertyAnimation(self.frame_4, b"pos")
            self.animation2.setDuration(250)
            self.animation2.setStartValue(QtCore.QPoint(1050,80))
            self.animation2.setEndValue(QtCore.QPoint(1440,80))
            self.animation2.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation2.start()
            
        self.frame_3.raise_()
        pos=self.frame_3.pos()
        self.animation=QPropertyAnimation(self.frame_3, b"pos")
        self.animation.setDuration(250)
        
        if pos.x()==1240:
            self.animation.setStartValue(QtCore.QPoint(1240,80))
            self.animation.setEndValue(QtCore.QPoint(1000,80))
        else:
            self.animation.setStartValue(QtCore.QPoint(1000,80))
            self.animation.setEndValue(QtCore.QPoint(1240,80))
        self.animation.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
        self.animation.start()
        
    def share(self):
               
        pos1=self.frame_3.pos()
        if pos1.x()==1000:
            self.animation1=QPropertyAnimation(self.frame_3, b"pos")
            self.animation1.setDuration(250)
            self.animation1.setStartValue(QtCore.QPoint(1000,80))
            self.animation1.setEndValue(QtCore.QPoint(1240,80))
            self.animation1.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation1.start()
            
        # opening the share slide menu
        self.frame_4.raise_()
        pos=self.frame_4.pos()
        self.animation=QPropertyAnimation(self.frame_4, b"pos")
        self.animation.setDuration(250)
        
        if pos.x()==1440:
            self.animation.setStartValue(QtCore.QPoint(1440,80))
            self.animation.setEndValue(QtCore.QPoint(1050,80))
        else:
            self.animation.setStartValue(QtCore.QPoint(1050,80))
            self.animation.setEndValue(QtCore.QPoint(1440,80))
        self.animation.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
        self.animation.start()
        
    def msg1(self):
        pos=self.frame_7.pos()
        self.animation=QPropertyAnimation(self.frame_7, b"pos")
        self.animation.setDuration(250)
        
        if pos.x()==1240:
            self.animation.setStartValue(QtCore.QPoint(1240,510))
            self.animation.setEndValue(QtCore.QPoint(1050,510))
        else:
            self.animation.setStartValue(QtCore.QPoint(1050,510))
            self.animation.setEndValue(QtCore.QPoint(1240,510))
        self.animation.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
        self.animation.start()
        
    def msg2(self):
        pos=self.frame_8.pos()
        self.animation=QPropertyAnimation(self.frame_8, b"pos")
        self.animation.setDuration(250)
        
        if pos.x()==1420:
            self.animation.setStartValue(QtCore.QPoint(1420,510))
            self.animation.setEndValue(QtCore.QPoint(1050,510))
        else:
            self.animation.setStartValue(QtCore.QPoint(1050,510))
            self.animation.setEndValue(QtCore.QPoint(1420,510))
        self.animation.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
        self.animation.start()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
