# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welserkit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie 
from PyQt5.QtCore import QPropertyAnimation, pyqtProperty,QTimer


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(460, 316)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 461, 301))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.movie = QMovie("sneutral.gif") 
        self.label.setMovie(self.movie) 
        self.movie.start() 
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(0, 300, 461, 16))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"border-style:none;\n"
"background-color: rgb(0, 0, 0);\n"
"color:rgb(73, 251, 53);\n"
"}\n"
"QProgressBar::chunk{\n"
"background-color:rgb(73, 251, 53);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
